name: lint the documentation
on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: yarn install

      - name: lint
        run: yarn run lint
